McbaExampleWithLogin/Controllers/BillPayController.cs
using McbaExample.Data;
using McbaExample.Models;
using McbaExampleWithLogin.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace McbaExample.Controllers
{
    public class BillPayController : Controller
    {
        private readonly McbaContext _context;

        private int CustomerID => HttpContext.Session.GetInt32(nameof(Customer.CustomerID)).Value;

        public BillPayController(McbaContext context) => _context = context;


        public async Task<IActionResult> CreateBill(int billID = 0)
        {
            HttpContext.Session.SetInt32("Mod", 0);
            ViewData["Mod"] = 0;
            var customer = await _context.Customers.Where(x => x.CustomerID == CustomerID).Include(x => x.Accounts).FirstOrDefaultAsync();
            var billviewmodel = new BillScheduleModel { Customer = customer };
            if (billID != 0)
            {
                var bill = await _context.BillPay.Where(x => x.BillPayID == billID).FirstOrDefaultAsync();
                billviewmodel.Billpay = bill;
                HttpContext.Session.SetInt32("Mod", billID);
                ViewData["Mod"] = billID;
            }
            var list = await _context.Payee.ToListAsync();
            billviewmodel.SetPayeeDictionary(list);
            return View(billviewmodel);

        }

        [HttpPost]


        //Method for prompting user to select account to view bills from
        public async Task<IActionResult> SelectAccount()
        {
            var accounts = await _context.Accounts.Where(x => x.CustomerID == CustomerID).ToListAsync();

            return View(accounts);
        }

        //Method for preparing BillSchedule page
        //Utilizes BillScheduleViewModel object
        public async Task<IActionResult> BillSchedule(int accountNumber)
        {
            var account = await _context.Accounts.Where(x => x.AccountNumber == accountNumber).Include(x => x.Bills).FirstOrDefaultAsync();
            var list = await _context.Payee.ToListAsync();
            BillSchedule bills = new BillSchedule(account, list);
            return View(bills);
        }

        //Method for returning partial view of balance total
        public async Task<IActionResult> SeeMyBalance(int id)
        {

            var account = await _context.Accounts.Where(x => x.AccountNumber == id).FirstOrDefaultAsync();
            return PartialView(account);

        }

        //Method for handling deletion of existing bills



    }
}

McbaExampleWithLogin/Controllers/LoginController.cs
using Microsoft.AspNetCore.Mvc;
using McbaExample.Data;
using McbaExample.Models;
using SimpleHashing;

namespace McbaExample.Controllers;

// Bonus Material: Implement global authorisation check.
//[AllowAnonymous]
[Route("/Mcba/SecureLogin")]
public class LoginController : Controller
{
    private readonly McbaContext _context;

    public LoginController(McbaContext context) => _context = context;

    public IActionResult Login() => View();

    [HttpPost]
    public async Task<IActionResult> Login(string loginID, string password)
    {
        var login = await _context.Logins.FindAsync(loginID);
        if(login == null || string.IsNullOrEmpty(password) || !PBKDF2.Verify(login.PasswordHash, password))
        { 
            ModelState.AddModelError("LoginFailed", "Login failed, please try again.");
            return View(new Login { LoginID = loginID });
        }

        // Login customer.
        HttpContext.Session.SetInt32(nameof(Customer.CustomerID), login.CustomerID);
        HttpContext.Session.SetString(nameof(Customer.Name), login.Customer.Name);

        return RedirectToAction("Index", "Customer");
    }

    [Route("LogoutNow")]
    public IActionResult Logout()
    {
        // Logout customer.
        HttpContext.Session.Clear();

        return RedirectToAction("Index", "Home");
    }
}

McbaExampleWithLogin/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - McbaExample</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-controller="Home" asp-action="Index">McbaExample</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav">
                        @{
                            var isLoggedIn = Context.Session.GetInt32(nameof(Customer.CustomerID)).HasValue;
                        }
                        @if(isLoggedIn) {
                            <li class="nav-item">
                                <span class="nav-link text-dark">
                                    Welcome, @Context.Session.GetString(nameof(Customer.Name))
                                </span>
                            </li>
                            
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Login" asp-action="Logout">Logout</a>
                            </li>
                        } else {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Login" asp-action="Login">Login</a>
                            </li>
                            
                        }
                    </ul>
                    <ul class="navbar-nav flex-grow-1">
    
                        @if(isLoggedIn) {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Customer" asp-action="Index">My Accounts</a>
                            </li>
                        }

                        @if(isLoggedIn) {
                         <li class="nav-item">
                            <div class="btn-group">
                                <a class="nav-link text-dark dropdown-toggle" data-toggle="dropdown">BillPay</a>
                                <div class="dropdown-menu">
                                    <a class="dropdown-item" asp-area="" asp-controller="BillPay" asp-action="CreateBill">Create Bill</a>
                                    <a class="dropdown-item" asp-area="" asp-controller="BillPay" asp-action="SelectAccount">Bill Schedule</a>
                                </div>
                            </div>
                        </li>
                        }

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - McbaExample - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", false)
</body>
</html>